sudo: required
language: generic

services: 
    - docker

before_install: 
    - docker build -t nic0d3mus/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nic0d3mus/docker-react npm run test